<table class="ac" WIDTH="490" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<tr>

<td colspan="2" class="al">
The Card Security Code (CSC) is a 3 digit number printed in the signature field on the back of your card. On some cards, the card number, or part of it, appears before the CSC. The number appears only on the card itself (not on your receipts or statements). 
</td></tr>

<tr>
<td colspan=2><hr noshade size="1"></td>
<td><img width=10 src="/cg/0.gif" border="0"></td>
</tr>

<tr>
<td><h3>VISA</h3>

The Verification Code is a three-digit number on the back of your Visa Credit card. The full credit card number or just the last four digits of your card number are in the signature box and at the end of the number is the verification Code.

</td><td><img SRC="/img/visa_card_security.gif" WIDTH="254" HEIGHT="186" ALT="" BORDER="0"></td>

<td><img width=10 src="/cg/0.gif" border="0"></td>
</tr>

<tr>
<td colspan=2><hr noshade size="1"></td>
</tr>

<tr>
<td><h3>MASTERCARD</h3>

The Verification Code is a three-digit number on the back of your MasterCard. The full credit card number or just the last four digits of your card number are in the signature box and at the end of the number is the verification Code.

</td><td><img SRC="/img/mc_card_security.gif" WIDTH="254" HEIGHT="186" ALT="" BORDER="0" ></td>

</tr>

<tr>
<td colspan=2><hr noshade size="1"></td>
</tr>


<tr>
<td><h3>AMERICAN EXPRESS</h3>
The Verification Code is a four-digit number on the front of the card above the credit card number on either the right or the left side of your American Express credit card.
</td>
<td><img SRC="/img/amex_card_security.gif" WIDTH="254" HEIGHT="186" ALT="" BORDER="0" ></td>

</tr>

</table>
</body>
</html>



